# Site settings
title: xpchen's blog
url: "http://xpchen0630.github.io"
baseurl: ""
timezone: Asia/Guangzhou
description: >
  a reading note about machine learning.

# Your information
email: stxpchen@foxmail.com
author: xpchen
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: a graduate student majoring in software engineering.
# twitter_username: twitter_username
github_username:  xpchen0630
profile_links:
  Email: "mailto:stxpchen@foxmail.com"
  # GitHub: "https://github.com/laobubu/jekyll-theme-EasyBook"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/
    Donate: /donate/

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
